[package]
name = "game-client"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
bevy = "0.19"
gltf = { version = "1.4", default-features = false, features = ["utils", "names"] }
game-core = { version = "0.1.0", path = "../game-core" }
game-net = { version = "0.1.0", path = "../game-net" }
pop3-format = { version = "0.1.0", path = "../pop3-format" }
